# ==================================================================================================
# --- Structure of the study ---
# ==================================================================================================
name: example_custom_ost

# List all useful files that will be used by executable in generations below
# These files are placed at the root of the study
dependencies:
  main_configuration: config_hllhc16.yaml
  custom_ost: custom_files/custom_ost.py

structure:
  # First generation is always at the root of the study
  # such that config_hllhc16.yaml is accessible as ../config_hllhc16.yaml
  generation_1:
    executable: custom_files/generation_1.py
