[tool.poetry]
name = "study-da"
version = "0.1.0"
description = "A tool to create large-scale DA simulations."
authors = ["Colas <colasdroin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
pandas = "^2.2.2"
pyyaml = "^6.0.1"
xmask = {path = "external_dependencies/xmask"}
cpymad = "^1.16.3"
ruamel-yaml = "^0.18.6"
jinja2 = "^3.1.4"
xsuite = "^0.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
